FROM python:3.9-slim

RUN pip install --no-cache-dir -r requirements.txt

# Copy and install Python dependencies
COPY scripts/requirements.txt .

# Set working directory
WORKDIR /app

# Copy your Python script(s)
COPY scripts/api.py .

# Default command
CMD ["python", "api.py"]